//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFarmacia.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int Codigo_Pedido { get; set; }
        public Nullable<System.DateTime> Fecha_Hora_Pedido { get; set; }
        public Nullable<System.DateTime> Fecha_Hora_Entrega { get; set; }
        public Nullable<int> Codigo_Direccion_Pedido { get; set; }
        public Nullable<int> Codigo_Personas { get; set; }
        public Nullable<int> Codigo_Detalle_Pedido { get; set; }
        public Nullable<int> Codigo_Cliente { get; set; }
        public Nullable<int> Codigo_Venta { get; set; }
        public Nullable<int> Numero_Comprobante { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Comprobante Comprobante { get; set; }
        public virtual Detalle_Pedido Detalle_Pedido { get; set; }
        public virtual Ubicacion_Pedido Ubicacion_Pedido { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
