//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmacia
    {
        public int Id_Farmacia { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Horario { get; set; }
        public Nullable<int> Id_Personas { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
