//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Nombre_Usuario { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<int> Codigo_Tipo_Usuario { get; set; }
    
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
    }
}
