//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFarmaciaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.pedido = new HashSet<pedido>();
        }
    
        public int Codigo_Venta { get; set; }
        public Nullable<int> Codigo_Cliente { get; set; }
        public Nullable<int> Id_Personas { get; set; }
        public Nullable<int> Codigo_Producto { get; set; }
        public Nullable<int> Codigo_Detalle_Venta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha_Venta { get; set; }
        public string Tipo_Venta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Detalle_Venta Detalle_Venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
